runtime: nodejs24

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

# Yaml reference: Adapted from Google Cloud docs, https://docs.cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=node.js#top